--Relational Schema (Database)
CREATE TABLE Project(
	PrID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Budget MONEY NOT NULL,
	CID INT,
	PRIMARY KEY(PrID),
	CONSTRAINT fk_customer
		FOREIGN KEY(CID)
			REFERENCES Customer(CID)
);

CREATE TABLE Customer(
	CID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	LID INT,
	PRIMARY KEY(CID),
	CONSTRAINT fk_location
		FOREIGN KEY(LID)
			REFERENCES Location(LID)
);

CREATE TABLE Location(
	LID INT GENERATED ALWAYS AS IDENTITY,
	Address VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	PRIMARY KEY(LID)
);

CREATE TABLE Department(
	DepID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	LID INT,
	PRIMARY KEY(DepID),
	CONSTRAINT fk_location --Change if can't have same name
		FOREIGN KEY(LID)
			REFERENCES Location(LID)
);

CREATE TABLE Employee(
	EmpID INT GENERATED ALWAYS AS IDENTITY,
	Email VARCHAR(255) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	DepID INT,
	PRIMARY KEY(EmpID),
	CONSTRAINT fk_department 
		FOREIGN KEY(DepID)
			REFERENCES Department(DepID)
);

CREATE TABLE UserGroup(
	GrID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	PRIMARY KEY(GrID)
);

CREATE TABLE Role(
	RoleID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	PRIMARY KEY(RoleID)
);
