--Relational Schema (Database)
--Tables/Entities
CREATE TABLE Project(
	PrID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Budget MONEY NOT NULL,
	CID INT,
	PRIMARY KEY(PrID),
	CONSTRAINT fk_customer
		FOREIGN KEY(CID)
			REFERENCES Customer(CID)
			ON UPDATE CASCADE
);

CREATE TABLE Customer(
	CID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	LID INT,
	PRIMARY KEY(CID),
	CONSTRAINT fk_location
		FOREIGN KEY(LID)
			REFERENCES Location(LID)
			ON UPDATE
);

CREATE TABLE Location(
	LID INT GENERATED ALWAYS AS IDENTITY,
	Address VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	PRIMARY KEY(LID)
);

CREATE TABLE Department(
	DepID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	LID INT,
	PRIMARY KEY(DepID),
	CONSTRAINT fk_location --Change if can't have same name
		FOREIGN KEY(LID)
			REFERENCES Location(LID)
			ON UPDATE
);

CREATE TABLE Employee(
	EmpID INT GENERATED ALWAYS AS IDENTITY,
	Email VARCHAR(255) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	DepID INT,
	PRIMARY KEY(EmpID),
	CONSTRAINT fk_department 
		FOREIGN KEY(DepID)
			REFERENCES Department(DepID)
			ON UPDATE CASCADE
);

CREATE TABLE UserGroup(
	GrID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	PRIMARY KEY(GrID)
);

CREATE TABLE Role(
	RoleID INT GENERATED ALWAYS AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	PRIMARY KEY(RoleID)
);

--Relationships
ALTER TABLE Project
ADD COLUMN startDate DATE,
ADD COLUMN deadline DATE;

CREATE TABLE Works(
	EmpID INT,
	PrID INT,
	started DATE,
	PRIMARY KEY(EmpID,PrID)
	CONSTRAINT fk_works_emp
		FOREIGN KEY(EmpID)
		REFERENCES Employee(EmpID) ON DELETE CASCADE,
	CONSTRAINT fk_works_pr
		FOREIGN KEY(PrID)
		REFERENCES Project(PrID) ON DELETE CASCADE
)

CREATE TABLE PartOf(
	GrID INT,
	EmpID INT,
	PRIMARY KEY(GrID,EmpID)
	CONSTRAINT fk_partof_gr
		FOREIGN KEY(GrID)
		REFERENCES UserGroup(GrID) ON DELETE CASCADE,
	CONSTRAINT fk_partof_emp
		FOREIGN KEY(EmpID)
		REFERENCES Employee(EmpID) ON DELETE CASCADE,
)


CREATE TABLE Has(
	EmpID INT,
	RoleID INT,
	Description TEXT,
	PRIMARY KEY(EmpID,RoleID)
	CONSTRAINT fk_has_emp
		FOREIGN KEY(EmpID)
		REFERENCES Employee(EmpID) ON DELETE CASCADE,
	CONSTRAINT fk_has_role
		FOREIGN KEY(RoleID)
		REFERENCES Role(RoleID) ON DELETE CASCADE
)
